export const ROUTES = {
  login: "/login",
  md: "/manager/dashboard",
  mr: "/manager/resources",
  mis: "/manager/inspection/status",
  mic: "/manager/inspection/schedule",
  mip: "/manager/inspection/special",
  mir: "/manager/report/view",
  mid: "/manager/report/history",
  mbn: "/manager/board",
  msp: "/manager/settings/profile",
  msc: "/manager/settings/common-code",
  msk: "/manager/settings/category",
  mslm: "/manager/settings/login-message",
  msl: "/manager/settings/license",
  msu: "/manager/settings/users",
  mst: "/manager/settings/checklist",
  msv: "/manager/settings/verification-code",
  mla: "/manager/settings/access-log",
  mle: "/manager/settings/error-log",
  msag: "/manager/settings/agent-auth",
  msi: "/manager/settings/system-info",
  sd: "/sentinel/dashboard",
  sll: "/sentinel/daily-inspection",
  ssl: "/sentinel/special-inspection",
  sbn: "/sentinel/board",
} as const;

export type RouteKey = keyof typeof ROUTES;
